package com.hybridtts.core

import android.content.ContentValues
import android.content.Context
import android.net.Uri
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import java.io.File
import java.io.FileOutputStream
import java.io.OutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

data class SubtitleCue(
    val index: Int,
    val startMs: Long,
    val endMs: Long,
    val text: String
)

enum class SubtitleFormat {
    SRT,   // SubRip (.srt)
    VTT,   // WebVTT (.vtt)
    ASS    // Advanced SubStation Alpha (.ass) with karaoke tags
}

object SubtitleAligner {

    // Converts raw text lines and total duration into synchronized cues
    fun generateCuesFromScript(scriptText: String, totalDurationSec: Double): List<SubtitleCue> {
        val rawSentences = scriptText.split(Regex("(?<=[.!?])\\s+")).filter { it.isNotBlank() }
        if (rawSentences.isEmpty()) return emptyList()

        val totalChars = rawSentences.sumOf { it.length }.coerceAtLeast(1)
        val cues = mutableListOf<SubtitleCue>()
        var currentMs = 0L

        for ((idx, sentence) in rawSentences.withIndex()) {
            val fraction = sentence.length.toDouble() / totalChars
            val segmentDurationMs = (fraction * totalDurationSec * 1000.0).toLong().coerceAtLeast(800L)
            val endMs = currentMs + segmentDurationMs

            cues.add(SubtitleCue(idx + 1, currentMs, endMs, sentence.trim()))
            currentMs = endMs + 100L // 100ms gap
        }

        return cues
    }

    fun buildSrt(cues: List<SubtitleCue>): String {
        val sb = StringBuilder()
        for (cue in cues) {
            sb.append("${cue.index}\n")
            sb.append("${formatTimestampSrt(cue.startMs)} --> ${formatTimestampSrt(cue.endMs)}\n")
            sb.append("${cue.text}\n\n")
        }
        return sb.toString().trim()
    }

    fun buildVtt(cues: List<SubtitleCue>): String {
        val sb = StringBuilder()
        sb.append("WEBVTT - Generated by HybridTTS Audio Workstation\n\n")
        for (cue in cues) {
            sb.append("${cue.index}\n")
            sb.append("${formatTimestampVtt(cue.startMs)} --> ${formatTimestampVtt(cue.endMs)}\n")
            sb.append("${cue.text}\n\n")
        }
        return sb.toString().trim()
    }

    fun buildAss(cues: List<SubtitleCue>): String {
        val sb = StringBuilder()
        sb.append("[Script Info]\nTitle: HybridTTS Master Subtitles\nScriptType: v4.00+\nPlayResX: 1920\nPlayResY: 1080\n\n")
        sb.append("[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n")
        sb.append("Style: Default,Arial,52,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,3,2,2,10,10,40,1\n\n")
        sb.append("[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n")

        for (cue in cues) {
            val start = formatTimestampAss(cue.startMs)
            val end = formatTimestampAss(cue.endMs)
            // Inject karaoke tag
            sb.append("Dialogue: 0,$start,$end,Default,,0,0,0,,{\\k30}${cue.text}\n")
        }
        return sb.toString().trim()
    }

    fun exportSubtitleFile(context: Context, content: String, format: SubtitleFormat): Result<String> {
        val extension = when (format) {
            SubtitleFormat.SRT -> "srt"
            SubtitleFormat.VTT -> "vtt"
            SubtitleFormat.ASS -> "ass"
        }

        val timestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US).format(Date())
        val fileName = "HybridTTS_Subtitles_$timestamp.$extension"

        return try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                val contentValues = ContentValues().apply {
                    put(MediaStore.MediaColumns.DISPLAY_NAME, fileName)
                    put(MediaStore.MediaColumns.MIME_TYPE, "text/plain")
                    put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS + "/HybridTTS")
                }

                val uri: Uri? = context.contentResolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, contentValues)
                if (uri != null) {
                    context.contentResolver.openOutputStream(uri)?.use { out: OutputStream ->
                        out.write(content.toByteArray(Charsets.UTF_8))
                    }
                    Result.success("Saved to Downloads/HybridTTS/$fileName")
                } else {
                    Result.failure(Exception("Could not create media store entry."))
                }
            } else {
                val dir = File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS), "HybridTTS")
                if (!dir.exists()) dir.mkdirs()
                val file = File(dir, fileName)
                FileOutputStream(file).use { it.write(content.toByteArray(Charsets.UTF_8)) }
                Result.success("Saved to ${file.absolutePath}")
            }
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    private fun formatTimestampSrt(ms: Long): String {
        val h = ms / 3600000
        val m = (ms % 3600000) / 60000
        val s = (ms % 60000) / 1000
        val millis = ms % 1000
        return String.format(Locale.US, "%02d:%02d:%02d,%03d", h, m, s, millis)
    }

    private fun formatTimestampVtt(ms: Long): String {
        val m = ms / 60000
        val s = (ms % 60000) / 1000
        val millis = ms % 1000
        return String.format(Locale.US, "%02d:%02d.%03d", m, s, millis)
    }

    private fun formatTimestampAss(ms: Long): String {
        val h = ms / 3600000
        val m = (ms % 3600000) / 60000
        val s = (ms % 60000) / 1000
        val cs = (ms % 1000) / 10 // centiseconds
        return String.format(Locale.US, "%01d:%02d:%02d.%02d", h, m, s, cs)
    }
}
